### ISSUE TITLE
Flatpak can get stuck when toggling "Start automatically at system boot"

### ISSUE THREAD

**Issue by K0-RR** [Merrit/nyrna#202]
```
flatpak run codes.merritt.Nyrna
Gtk-Message: 10:33:33.794: Failed to load module "appmenu-gtk-module"

(nyrna:2): Gdk-CRITICAL **: 10:33:33.820: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

(nyrna:2): Gdk-CRITICAL **: 10:33:35.253: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
flutter:   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   ERROR │ org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ #0   DBusClient._callMethod (package:dbus/src/dbus_client.dart:1126)
flutter:   ERROR │ #1   <asynchronous suspension>
flutter:   ERROR │ #2   DBusClient.callMethod (package:dbus/src/dbus_client.dart:621)
flutter:   ERROR │ #3   <asynchronous suspension>
flutter:   ERROR │ #4   XdgBackgroundPortal.requestBackground.<anonymous closure> (package:xdg_desktop_portal/src/xdg_background_portal.dart:68)
flutter:   ERROR │ #5   <asynchronous suspension>
flutter:   ERROR │ #6   XdgPortalRequest._onListen (package:xdg_desktop_portal/src/xdg_portal_request.dart:39)
flutter:   ERROR │ #7   <asynchronous suspension>
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ ⛔ Uncaught platform error
flutter:   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by Merrit** [comment]
Hey, thanks for opening the issue~

Could you please provide the following:

- Distro / version
- Nyrna version

Thanks!

**Comment by K0-RR** [comment]
Rhino Linux (Ubuntu rolling)
Nyrna 2.18.0

**Comment by Merrit** [comment]
This is happening because your system is not offering `org.freedesktop.portal.Background`.

If you are using GNOME it should be provided by `xdg-desktop-portal-gnome`. I tried spinning up Rhino Linux in a VM, but even after installing `xdg-desktop-portal-gnome` it still doesn't work.

You'll have to check with them as to why the distro isn't providing it as expected.
